---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld-app
      version: blue
  template:
    metadata:
      name: hello-blue-whale-pod
      labels:
        app: hello-whale-app
        version: blue
    spec:
      containers:
        - name: helloworld-container
          image: mjordalopez/modeling-java
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: helloworld-app
spec:
  selector:
    app: helloworld-app
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
